name: Automatically update and run pre-commit hooks

# Run daily at midnight.
on:
  workflow_dispatch:
  # schedule:
  #   - cron: '*/5 * * * *'

jobs:
  # This workflow contains a single job called "autoupdate"
  autoupdate:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set the name of the branch for these changes
        id: branch
        run: echo "::set-output name=branchname::pre-commit-autoupdate"

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '>=3'

      - name: Install pre-commit
        run: pip install pre-commit

      - name: ${{ github.workflow }}
        run: |
          pre-commit autoupdate
          until pre-commit run --all-files
          do
            echo "Re-running pre-commits..."
          done

      - name: Create a new branch pre-commit-autoupdate and push the changes to it
        run: |
          git config user.name "GitHub"
          git config user.email "noreply@github.com"
          git checkout -B ${{ steps.branch.outputs.branchname }}
          git add .
          git commit -m "${{ github.workflow }}"
          git push -fu origin ${{ steps.branch.outputs.branchname }}

      - name: Create pull request
        id: pr
        uses: peter-evans/create-pull-request@v3
        with:
          branch: pre-commit-autoupdate
          base: master
          commit-message: ${{ github.workflow }}
          title: ${{ github.workflow }}

      - name: Set the file name for the Towncrier news fragment
        id: newsfile
        run: echo "::set-output name=filename::${{ steps.pr.outputs.pull-request-number }}.misc"

      - name: Make a Towncrier news fragment and push it to the branch
        if: ${{ steps.pr.outputs.pull-request-number }}
        run: |
          echo "${{ github.workflow }}" > ${{ steps.newsfile.outputs.filename }}
          git add ${{ steps.newsfile.outputs.filename }}
          git commit -m "Add news fragment"
          git push origin ${{ steps.branch.outputs.branchname }}
